// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protocol {

  /// <summary>Holder for reflection information generated from ProtoID.proto</summary>
  public static partial class ProtoIDReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoID.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoIDReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1Qcm90b0lELnByb3RvEghQcm90b2NvbCovCgdQcm90b0lEEhEKDVJlcV9I",
            "ZWFydEJlYXQQABIRCg1BY2tfSGVhcnRCZWF0EAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protocol.ProtoID), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ProtoID {
    [pbr::OriginalName("Req_HeartBeat")] ReqHeartBeat = 0,
    [pbr::OriginalName("Ack_HeartBeat")] AckHeartBeat = 1,
  }

  #endregion

}

#endregion Designer generated code
